### ISSUE TITLE
Which version of puppet is currently supported?

### ISSUE THREAD

**Issue by amorcomb** [maxlinc/puppet-decrypt#2]
Running the gem install on puppet 2.7 does not install the crypt subcommand properly and therefor puppet crypt encrypt/decrypt is not functioning (subcommand not found).

**Comment by maxlinc** [comment]
Travis-CI is set to test many combinations of ruby and puppet versions, including Puppet 2.7.  You can see the latest build here:
https://travis-ci.org/maxlinc/puppet-decrypt

If you are running from a directory containing a Gemfile, you may need to add it instead of using gem install.  If I install puppet and puppet-decrypt without a Gemfile it works.  If I add a Gemfile with puppet (but not puppet-decrypt) then it does not.

If that's not your problem, please send your exact puppet and ruby version (and other relevant info - bundler, rvm, rbenv, etc.) and I'll try to reproduce the problem.
Can you send some extra info - your exact ruby and puppet version.

**Comment by amorcomb** [comment]
Thanks for the quick response. Installing on my local mac with puppet 3
works seamlessly.

Here's the sequence on my linux box:

$ sudo gem install puppet-decrypt
Successfully installed puppet-decrypt-0.0.4
1 gem installed
Installing ri documentation for puppet-decrypt-0.0.4...
Installing RDoc documentation for puppet-decrypt-0.0.4...

$ find / -name puppet-decrypt
/usr/lib/ruby/gems/1.8/gems/puppet-decrypt-0.0.4/lib/puppet-decrypt

$ puppet crypt encrypt secret
Error: Unknown Puppet subcommand 'crypt'
See 'puppet help' for help on available puppet subcommands

ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
puppet 2.7.19

On Wed, Jul 10, 2013 at 1:43 PM, maxlinc notifications@github.com wrote:

> Travis-CI is set to test many combinations of ruby and puppet versions,
> including Puppet 2.7. You can see the latest build here:
> https://travis-ci.org/maxlinc/puppet-decrypt
> 
> If you are running from a directory containing a Gemfile, you may need to
> add it instead of using gem install. If I install puppet and puppet-decrypt
> without a Gemfile it works. If I add a Gemfile with puppet (but not
> puppet-decrypt) then it does not.
> 
> If that's not your problem, please send your exact puppet and ruby version
> (and other relevant info - bundler, rvm, rbenv, etc.) and I'll try to
> reproduce the problem.
> Can you send some extra info - your exact ruby and puppet version.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/maxlinc/puppet-decrypt/issues/2#issuecomment-20771676
> .

## 

C. Andrew Morcomb, _DevOps@__api_*gee  |
*amorcomb@apigee.commjager@apigee.com
 |  mobile: +1.408.219.8442  |  Skype: ungulate00  |  Alt GTalk:
morcomba@gmail.com

**Comment by maxlinc** [comment]
Okay, the problem is probably ruby 1.8.7.  It was [officially retired](http://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/) at the end of June.

I don't plan to support ruby 1.8.7.  I realize is inconvenient since 1.8.7 is still the default ruby for many users.  I know some projects plan to keep supporting ruby 1.8.7, but for a newer project, especially one that has a focus on security, I do not think it makes sense.

I'll update the gemspec to require ruby > 1.9.0.

**Comment by amorcomb** [comment]
Thanks. Running the gem install using ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux] and puppet 2.7.0 yields the same behavior however. Where should crypt.rb be installed in relation to puppet?

/usr/local/rvm/gems/ruby-2.0.0-p247/gems/puppet-decrypt-0.0.4/lib/puppet-decrypt

**Comment by maxlinc** [comment]
It's not clear it should work, since as far as I can tell [Feature #7788: Puppet should allow rubygems to deliver new functionality](http://projects.puppetlabs.com/issues/7788) was not backported to 2.7.

However, I am able to get it to work on ruby 2.0.0 and puppet 2.7 under some conditions.  I've got puppet installed as a gem, and I need to have a Gemfile/Gemfile.lock in the current directory (without those, `puppet help crypt` works, but `puppet crypt ...` doesn't).

I'm going to investigate installing via puppet module tool instead of rubygems, and see if that simplifies things.

**Comment by amorcomb** [comment]
Thanks for all the feedback. I was able to get this to work under the following conditions:

ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
puppet 2.7.19

$ gem install encryptor
$ puppet module install devopsy/puppet_decrypt

Note the full path on the module install. Also, puppetlabs confirmed that puppet faces subcommands are only supported at v. 3.1.1

AWS only uses ruby 1.8.7 (still) on all it's Linux images, so this dependency is going to be around a good while longer.
